#!/bin/sh

[ -f $HOME/.config/containers/storage.conf ] && exit 0

[ ! -d $HOME/.config/containers ] && mkdir $HOME/.config/containers

cat > $HOME/.config/containers/storage.conf <<EOD
[storage]
driver="overlay"
graphroot="/tmp/\$USER/containers/storage"

[storage.options.overlay]
mount_program="/usr/bin/fuse-overlayfs"
EOD
